base-files: emos-init: create overlay directories if nonexistent
We can produce devices with empty /config and do not need any special
handling for this partition during factory reset this way.

Signed-off-by: Matthias Schiffer <matthias.schiffer@tq-group.com>

diff --git a/recipes-core/base-files/files/emos-init b/recipes-core/base-files/files/emos-init
--- a/recipes-core/base-files/files/emos-init
+++ b/recipes-core/base-files/files/emos-init
@@ -3,12 +3,8 @@
 export PATH=/usr/bin:/bin:/usr/sbin:/sbin
 
 
-msg() {
-	echo "$1" >/dev/console
-}
-
 fatal() {
-	msg "$1"
+	echo >&2 "$1"
 	exit 1
 }
 
@@ -17,16 +13,20 @@ fatal() {
 
 
 [ -e /dev/console ] || mount -t devtmpfs devtmpfs /dev || fatal '/dev mount failed.'
+
+# Initialize stdout and stderr
+exec >/dev/console 2>/dev/console
+
 mount -t proc proc /proc || fatal '/proc mount failed.'
 mount -t sysfs sysfs /sys || fatal '/sys mount failed.'
 
-(
-        mount -o ro /dev/mmcblk0p9 /auth && \
-        mount /dev/mmcblk0p7 /config && \
-        mount -t overlay \
-                -o lowerdir=/auth/etc:/etc,upperdir=/config/etc,workdir=/config/work \
-                overlay /etc \
-) || fatal '/etc overlay mount failed.'
+mount -o ro /dev/mmcblk0p9 /auth || fatal '/auth mount failed.'
+mount /dev/mmcblk0p7 /config || fatal '/config mount failed.'
+
+mkdir -p /config/etc /config/work || fatal 'Unable to create required overlayfs directories.'
+mount -t overlay \
+	-o lowerdir=/auth/etc:/etc,upperdir=/config/etc,workdir=/config/work \
+	overlay /etc || fatal '/etc overlay mount failed.'
 
 mount /dev/mmcblk0p8 /data || fatal '/data mount failed.'
 mount /dev/mmcblk0p5 /apps || fatal '/apps mount failed.'
