emcfg: init: reorder factory reset to make it more robust
We format /update last now, and trigger another reformat of /update when
mounting the partition fails. See the added code comment for a detailed
explanation.

Signed-off-by: Matthias Schiffer <matthias.schiffer@tq-group.com>

diff --git a/recipes-core/emcfg/files/em-init b/recipes-core/emcfg/files/em-init
--- a/recipes-core/emcfg/files/em-init
+++ b/recipes-core/emcfg/files/em-init
@@ -40,14 +40,6 @@ stop_haveged() {
 factory_reset() {
 	echo >&2 'Performing factory reset.'
 
-	# Gather entropy for mkfs.ext4
-	start_haveged
-
-	mkfs.ext4 -Fvj $DEV_APPS
-	mkfs.ext4 -Fvj $DEV_UPDATE
-	mkfs.ext4 -Fvj $DEV_CFGLOG
-	mkfs.ext4 -Fvj $DEV_DATA
-
 	mount -t tmpfs apps /apps
 	mkdir /apps/installed
 	mount --bind /opt/apps /apps/installed
@@ -59,6 +51,22 @@ factory_reset() {
 		$TBIN/tboot
 		$TBIN/tcmd SPI_CMD_CLEAR_REGISTERS
 	fi
+
+	# Gather entropy for mkfs.ext4
+	start_haveged
+
+	mkfs.ext4 -Fvj $DEV_APPS
+	mkfs.ext4 -Fvj $DEV_CFGLOG
+	mkfs.ext4 -Fvj $DEV_DATA
+}
+
+update_reset() {
+	echo >&2 'Formatting /update.'
+
+	# Gather entropy for mkfs.ext4
+	start_haveged
+
+	mkfs.ext4 -Fvj $DEV_UPDATE
 }
 
 
@@ -75,11 +83,25 @@ mount -t sysfs sysfs /sys || fatal '/sys mount failed.'
 mount -t tmpfs -o nosuid,nodev,mode=755 run /run || fatal '/run mount failed.'
 
 # Mount eMMC partitions
-mount -o nosuid,nodev $DEV_UPDATE /update || fatal '/update mount failed.'
+
+# This check handles power loss during factory reset.
+# As /update is formatted last, there are two possiblities for unfinsihed
+# factory resets:
+# 1) /update is not formatted yet. In this case, /update can still be mounted
+#    and /update/factory-reset exists. The factory reset will be repeated on the
+#    next boot.
+# 2) /update is in the process of being formatted when the factory reset occurs.
+#    In this case, the following mount may fail. In result, /update will be
+#    formatted again, completing the factory reset.
+if ! mount -o nosuid,nodev $DEV_UPDATE /update; then
+	update_reset
+	mount -o nosuid,nodev $DEV_UPDATE /update || fatal '/update mount failed.'
+fi
 
 if [ -e /update/factory-reset ]; then
 	umount /update
 	factory_reset
+	update_reset
 	mount -o nosuid,nodev $DEV_UPDATE /update || fatal '/update mount failed.'
 fi
 
