recipes-core/emcfg/files/em-init: add service partition
Signed-off-by: Christoph Krutz <christoph.krutz@tq-group.com>

diff --git a/recipes-core/emcfg/files/em-init b/recipes-core/emcfg/files/em-init
--- a/recipes-core/emcfg/files/em-init
+++ b/recipes-core/emcfg/files/em-init
@@ -7,6 +7,7 @@ DEV_UPDATE=/dev/mmcblk0p6
 DEV_CFGLOG=/dev/mmcblk0p7
 DEV_DATA=/dev/mmcblk0p8
 DEV_AUTH=/dev/mmcblk0p9
+DEV_SERVICE=/dev/mmcblk0p10
 
 MOUNT_OPTS_RO="nosuid,nodev,ro"
 MOUNT_OPTS_RW="nosuid,nodev,noatime"
@@ -196,6 +197,11 @@ check_filesystem $DEV_APPS   "/apps"
 check_filesystem $DEV_CFGLOG "/cfglog"
 check_filesystem $DEV_DATA   "/data"
 
+if [ -e $DEV_SERVICE ]; then
+	check_filesystem $DEV_SERVICE "/cfglog/service"
+fi
+
+
 # Reboot if fsck wants it
 $FSCK_REBOOT && reboot
 
@@ -209,6 +215,12 @@ if $BACKUP_RESTORE  && ! $END_OF_LIFE; then
 	umount /update
 	update_reset
 	mount -o $MOUNT_OPTS_RW $DEV_UPDATE /update || fatal '/update mount failed.'
+fi
+
+# mount service partition if it exists
+if [ -e $DEV_SERVICE ]; then
+	mkdir -p /cfglog/service
+	mount -o $MOUNT_OPTS_RW $DEV_SERVICE /cfglog/service || fatal '/cfglog/service mount failed.'
 fi
 
 if ! mount -o $MOUNT_OPTS_RW $DEV_DATA /data; then
